# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e1b121f50cf5e555e31231ea07be0298063e1d9ae365ba6922ab0ed9c4dc338eef8e2077e29aeb668c779ba0d3f79ec8590c467e89f88a998b084732ff7b5b5

test:
  secret_key_base: 96790034f1ad73f22190d0327c1c43673395f3842ac4b8a29420ba932e49b0aef977d70106302ee5657aa065a3e80c02f476298f6e30299e0dbd0e8a7767e6c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
